[2024-02-29T22:42:04.111+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_upload.extract_weather_task manual__2024-02-29T22:42:03.394055+00:00 [queued]>
[2024-02-29T22:42:04.118+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_upload.extract_weather_task manual__2024-02-29T22:42:03.394055+00:00 [queued]>
[2024-02-29T22:42:04.119+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-02-29T22:42:04.127+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_weather_task> on 2024-02-29 22:42:03.394055+00:00
[2024-02-29T22:42:04.131+0000] {standard_task_runner.py:57} INFO - Started process 170 to run task
[2024-02-29T22:42:04.133+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_data_upload', 'extract_weather_task', 'manual__2024-02-29T22:42:03.394055+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_upload_dag.py', '--cfg-path', '/tmp/tmpsbgse5o1']
[2024-02-29T22:42:04.134+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask extract_weather_task
[2024-02-29T22:42:04.170+0000] {task_command.py:416} INFO - Running <TaskInstance: weather_data_upload.extract_weather_task manual__2024-02-29T22:42:03.394055+00:00 [running]> on host 87360dca8529
[2024-02-29T22:42:04.223+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_upload' AIRFLOW_CTX_TASK_ID='extract_weather_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-29T22:42:03.394055+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-29T22:42:03.394055+00:00'
[2024-02-29T22:42:05.219+0000] {logging_mixin.py:151} INFO - HTTP Error: 401 Client Error: Unauthorized for url: https://api.openweathermap.org/data/3.0/onecall/day_summary?lat=37.774929&lon=-122.419415&date=2024-02-26
[2024-02-29T22:42:05.219+0000] {logging_mixin.py:151} INFO - Response text: {"cod":401, "message": "Please note that using One Call 3.0 requires a separate subscription to the One Call by Call plan. Learn more here https://openweathermap.org/price. If you have a valid subscription to the One Call by Call plan, but still receive this error, then please see https://openweathermap.org/faq#error401 for more info."}
[2024-02-29T22:42:05.223+0000] {python.py:194} INFO - Done. Returned value was: Empty DataFrame
Columns: []
Index: []
[2024-02-29T22:42:05.254+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=weather_data_upload, task_id=extract_weather_task, execution_date=20240229T224203, start_date=20240229T224204, end_date=20240229T224205
[2024-02-29T22:42:05.310+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-02-29T22:42:05.327+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
