[2024-03-01T00:56:21.471+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_upload.extract_weather_task scheduled__2024-02-29T00:00:00+00:00 [queued]>
[2024-03-01T00:56:21.477+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_upload.extract_weather_task scheduled__2024-02-29T00:00:00+00:00 [queued]>
[2024-03-01T00:56:21.478+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-03-01T00:56:21.486+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_weather_task> on 2024-02-29 00:00:00+00:00
[2024-03-01T00:56:21.489+0000] {standard_task_runner.py:57} INFO - Started process 399 to run task
[2024-03-01T00:56:21.492+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_data_upload', 'extract_weather_task', 'scheduled__2024-02-29T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_upload_dag.py', '--cfg-path', '/tmp/tmp3yzpuxkw']
[2024-03-01T00:56:21.493+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask extract_weather_task
[2024-03-01T00:56:21.527+0000] {task_command.py:416} INFO - Running <TaskInstance: weather_data_upload.extract_weather_task scheduled__2024-02-29T00:00:00+00:00 [running]> on host 87360dca8529
[2024-03-01T00:56:21.577+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_upload' AIRFLOW_CTX_TASK_ID='extract_weather_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-29T00:00:00+00:00'
[2024-03-01T00:56:22.984+0000] {logging_mixin.py:151} INFO - HTTP Error: 401 Client Error: Unauthorized for url: https://api.openweathermap.org/data/3.0/onecall/day_summary?lat=37.774929&lon=-122.419415&date=2024-02-27
[2024-03-01T00:56:22.984+0000] {logging_mixin.py:151} INFO - Response text: {"cod":401, "message": "Please note that using One Call 3.0 requires a separate subscription to the One Call by Call plan. Learn more here https://openweathermap.org/price. If you have a valid subscription to the One Call by Call plan, but still receive this error, then please see https://openweathermap.org/faq#error401 for more info."}
[2024-03-01T00:56:22.987+0000] {python.py:194} INFO - Done. Returned value was: Empty DataFrame
Columns: []
Index: []
[2024-03-01T00:56:23.016+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=weather_data_upload, task_id=extract_weather_task, execution_date=20240229T000000, start_date=20240301T005621, end_date=20240301T005623
[2024-03-01T00:56:23.068+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-03-01T00:56:23.086+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
